# Generated by Django 5.0.1 on 2024-01-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=255, unique=True)),
                ('product_code', models.CharField(max_length=255)),
                ('complete_date_target', models.DateField()),
                ('comments', models.TextField()),
                ('bom_received', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('product', models.CharField(max_length=255)),
                ('presentation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.CharField(max_length=255)),
                ('target_start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_priority.batch')),
            ],
        ),
    ]
