# Generated by Django 5.0.1 on 2024-01-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0004_alter_batch_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
