# Generated by Django 5.0.1 on 2024-01-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0005_alter_batch_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
