# Generated by Django 5.0.1 on 2024-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0006_batch_batch_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
