# Generated by Django 5.0.1 on 2024-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0007_alter_bay_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='samples_received',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
