# Generated by Django 5.0.1 on 2024-01-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0008_batch_samples_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetdate',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetdate', to='batch_priority.batch'),
        ),
    ]
