# Generated by Django 5.0.1 on 2024-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0009_alter_targetdate_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='production_check',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
