# Generated by Django 5.0.1 on 2024-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0010_batch_production_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='production_check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
