# Generated by Django 5.0.1 on 2024-01-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0015_batch_batch_complete_date_batch_completed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='comments',
            new_name='notes',
        ),
    ]
