# Generated by Django 5.0.1 on 2024-01-18 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='manufacture_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
