# Generated by Django 5.0.1 on 2024-01-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0019_historicalbatch_historicaltargetdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltargetdate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetdate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
