# Generated by Django 5.0.2 on 2024-02-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0023_historicaldailydiscussioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_type', models.CharField(max_length=255, unique=True)),
                ('containers_per_tray', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch_priority.tray'),
        ),
    ]
