# Generated by Django 5.0.2 on 2024-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_priority', '0024_tray_product_tray'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='tray_size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
